### ISSUE TITLE
App release crash on android

### ISSUE THREAD

**Issue by lgArlequin** [lubritto/Pdf_Viewer_Plugin#1]
I was testing the plugin, it works fine on a one1 with android 8, but when I release the application it crash when start on some phones.
I have no way of checking what is happening.
Any ideas?

**Comment by willvlad** [comment]
@lgArlequin hey man - I'm in the same boat of trying to find a non-crashing pdf viewer plugin for flutter. Have you managed to find one or fixed any of the crashing ones?

**Comment by lgArlequin** [comment]
Unfortunately not. 
Simply use the webview plugin and a google proxy to load the pdf.
https://pub.dartlang.org/packages/flutter_webview_plugin
and the pdf url:
`https://drive.google.com/viewerng/viewer?embedded=true&url=http://yourdomain.com/yourpdf.pdf`

**Comment by willvlad** [comment]
Yes, that's what I found too! How do you find the load times though? Seems a bit slow, no?

**Comment by Borduni** [comment]
Yeah. WebView isnt a good option. I also havent found any good working inline pdf viewer plugin for android

**Comment by lubritto** [comment]
Hey guys, the plugin was updated to use platform-view. I will close this issue and If you find an error again, please open another issue.
