### ISSUE TITLE
APK size is exploding after adding pdf_viewer_plugin

### ISSUE THREAD

**Issue by nilsreichardt** [lubritto/pdf_viewer_plugin#23]
Our APK size without `pdf_viewer_plugin` is 20 MB. After adding the plugin our APK size is 50 MB. `minifyEnabled` is enabled.

**Comment by techieasif** [comment]
@AndroidNils  Same thing happened to me.
Did you get any solution?

**Comment by AndroidNils** [comment]
Unfortunately not for this plugin. I switch to `native_pdf_view`. It's not perfect, because APK size is 30 MB.

**Comment by diegolaballos** [comment]
I'd try to use AAB (Android App Bundles) instead of APK to include only the needed native libraries. I guess it uses some C/C++ code that makes the APK bigger because it includes the libraries for all the different architectures.

**Comment by yskhs07** [comment]
Split your apk's by building different architecture apk using ndk filter 
use this in app/build.gradle
For 32-bit Apk
 ndk {
      abiFilters 'armeabi-v7a'  // For 32-bit APK
    }
For 64-bit apk
 ndk {
      abiFilters 'arm64-v8a'  // For 64-bit APK
    }

Also I've also seen the while using flutter build apk --release I get larger apk while using flutter run --release, it is lower so I use flutter run --release with signed gradle file while I need to upload my app to playstore.

**Comment by lubritto** [comment]
The apk size is due to the android plugin used. Unfortunately, there are no many free options, I'm using the best one available for this plugin.
