### ISSUE TITLE
Can't load pdf file on iOS simulator

### ISSUE THREAD

**Issue by dochanhca** [lubritto/pdf_viewer_plugin#25]
I added this line to Info.plist file:
`<key>io.flutter.embedded_views_preview</key>
<string>YES</string>`
I getting this error after open pdf file on iOS Simulator:

`[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'pdf_viewer_plugin')
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:168:41)
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:621:71)
#4      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:571:5)
#5      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:581:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#8      Element.inflateWidget (p<…>`

**Comment by lubritto** [comment]
Should be fixed cleaning the project with the 'flutter clean' command
