### ISSUE TITLE
Infinite loading of 'fetchPost' function

### ISSUE THREAD

**Issue by bulgariamitko** [lubritto/pdf_viewer_plugin#36]
This plugin worked great for me until I replace the link for the PDF file with google drive PDF and then Google restricted my account for sending too many requests to there server. Then I saw that the function 'fetchPost' was sending requests to the link even when the file was already send and showed in the screen. Clearly this behaviour is not intend i guess and it is bad experience for the server sending so many requests to the back-end. Please let me know if this issue can be fixed somehow.

**Comment by lubritto** [comment]
try again using the latest version example
