### ISSUE TITLE
Is there anyone else with an error updating the component version? (1.0.1 - Dec 10, 2020)

### ISSUE THREAD

**Issue by GustavoFior** [lubritto/Pdf_Viewer_Plugin#46]
C:\flutter.pub-cache\hosted\pub.dartlang.org\pdf_viewer_plugin-1.0.1\android\src\main\java\com\example\pdfviewerplugin\PdfViewer.java:25: error: cannot find symbol
        Intent i = new Intent(this, Wakeup.class);
        symbol:   class Intent
        location: class PdfViewer

**Comment by lubritto** [comment]
Hey @GustavoFior, sorry for this. I just accept a PR and goes with this problem. I already fix it in the last version and updated the platform view implementation. Now you can set `PdfView.platform = SurfaceAndroidPdfViewer();` to avoid hot reload problems.
