### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by emersonsiega** [lubritto/Pdf_Viewer_Plugin#47]
Hi there

There's any plans to migrate this package to supports null-safety?

**Comment by LucPham** [comment]
> Hi there
> 
> There's any plans to migrate this package to supports null-safety?

yah, the same question

**Comment by boskokg** [comment]
is this plugin dead?

**Comment by boskokg** [comment]
For others: You can use a fork that has null safety, update android sdk for PDF rendering and fixed jcenter repository.

  pdf_viewer_plugin:
    git:
      url: https://github.com/boskokg/Pdf_Viewer_Plugin/
      ref: master

**Comment by lubritto** [comment]
Fix is already published in the pub dev, also with a fix for the android hot reload and orientation issue

**Comment by boskokg** [comment]
@lubritto can you please check commits on my fork since there is newer version of android part that has better rendering performance and fixed several issues and also fixed maven central and target sdk changed to 30.

https://github.com/boskokg/Pdf_Viewer_Plugin/
