### ISSUE TITLE
(Bug) some time it is no showd in the display.

### ISSUE THREAD

**Issue by normidar** [lubritto/pdf_viewer_plugin#8]
my code just looks like the Example  where in your project, when it is run The logs looks like this :
`
I/m.dehm.demo_ap( 6218): NativeAlloc concurrent copying GC freed 14598(696KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 1724KB/3449KB, paused 23us total 101.821ms
` 
when it is no run that is no logs.

**Comment by normidar** [comment]
I'm loaded by local, but I think it is the same with load in the net just looks like the Example.

**Comment by lubritto** [comment]
Hey @normidar, your problem is just when you update the state after the first load right?

**Comment by myselfuser1** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by normidar** [comment]
I am no using this plugin now, close.
